name: The Remote Manifesto
markdown: redcarpet
pygments: true
exclude: [main.scss, config.rb, build]
description: The personal website of Paddy Oâ€™Hanlon on design and life
url: http://remotemanifesto.com/
